package main

import (
	"bytes"
	"context"
	"fmt"
	"image"
	"image/color"
	"image/draw"
	"image/jpeg"
	"os"
	"path/filepath"
	"strings"
	"time"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"
	"golang.org/x/image/math/fixed"
)

func loadDetailFont() (*opentype.Font, error) {
	paths := []string{os.Getenv("DETAIL_FONT_PATH"), "/usr/share/fonts/noto/NotoSansCJK-Regular.ttc", "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc", filepath.Join(os.Getenv("WINDIR"), "Fonts", "msyh.ttc")}
	for _, path := range paths {
		if path == "" {
			continue
		}
		data, err := os.ReadFile(path)
		if err != nil {
			continue
		}
		collection, err := opentype.ParseCollection(data)
		if err != nil {
			continue
		}
		return collection.Font(0)
	}
	return nil, fmt.Errorf("详情排版缺少中文字体，请安装 font-noto-cjk 或设置 DETAIL_FONT_PATH")
}

func detailTextLines(face font.Face, text string, width int) ([]string, error) {
	var lines []string
	line := ""
	for _, r := range strings.TrimSpace(text) {
		if r == '\n' {
			lines = append(lines, line)
			line = ""
			continue
		}
		if _, ok := face.GlyphAdvance(r); !ok {
			return nil, fmt.Errorf("详情字体不支持字符 %q", r)
		}
		if line != "" && font.MeasureString(face, line+string(r)).Ceil() > width {
			lines = append(lines, line)
			line = ""
		}
		line += string(r)
	}
	if line != "" {
		lines = append(lines, line)
	}
	return lines, nil
}

// Typography is rasterized from the approved strings, never generated by the
// image model. A separate caption band keeps text off product details.
func layoutDetailModule(img image.Image, section map[string]interface{}, typeface *opentype.Font) (image.Image, error) {
	b := img.Bounds()
	w := b.Dx()
	if w < 64 || w > 4096 || b.Dy() < 1 || b.Dy() > 8192 {
		return nil, fmt.Errorf("详情模块尺寸超出排版范围")
	}
	margin := w / 18
	kind := strings.ToLower(strings.TrimSpace(stringAny(section["type"])))
	centered := kind == "hero" || kind == "closing"
	titleSize, bodySize := float64(w)*0.046, float64(w)*0.026
	if kind == "hero" {
		titleSize *= 1.12
	}
	titleFace, err := opentype.NewFace(typeface, &opentype.FaceOptions{Size: titleSize, DPI: 72, Hinting: font.HintingFull})
	if err != nil {
		return nil, err
	}
	defer titleFace.Close()
	bodyFace, err := opentype.NewFace(typeface, &opentype.FaceOptions{Size: bodySize, DPI: 72, Hinting: font.HintingFull})
	if err != nil {
		return nil, err
	}
	defer bodyFace.Close()
	title := strings.TrimSpace(stringAny(section["copy_title"]))
	points := stringSlice(section["copy_points"])
	if title == "" && len(points) > 0 {
		title, points = points[0], points[1:]
	}
	titleLines, err := detailTextLines(titleFace, title, w-2*margin)
	if err != nil {
		return nil, err
	}
	var bodyLines []string
	for _, point := range points {
		lines, err := detailTextLines(bodyFace, point, w-2*margin)
		if err != nil {
			return nil, err
		}
		bodyLines = append(bodyLines, lines...)
	}
	if len(titleLines) > 3 || len(bodyLines) > 6 {
		return nil, fmt.Errorf("详情文案过长，请缩短标题和说明后重试")
	}
	titleHeight, bodyHeight := int(titleSize*1.4), int(bodySize*1.6)
	header := 0
	if len(titleLines)+len(bodyLines) > 0 {
		header = margin*2 + len(titleLines)*titleHeight + len(bodyLines)*bodyHeight
	}
	canvas := image.NewRGBA(image.Rect(0, 0, w, header+b.Dy()))
	draw.Draw(canvas, canvas.Bounds(), &image.Uniform{C: color.RGBA{248, 247, 244, 255}}, image.Point{}, draw.Src)
	draw.Draw(canvas, image.Rect(0, header, w, header+b.Dy()), img, b.Min, draw.Src)
	d := font.Drawer{Dst: canvas, Src: image.NewUniform(color.RGBA{45, 45, 43, 255}), Face: titleFace}
	y := margin
	for _, line := range titleLines {
		x := margin
		if centered {
			x = (w - font.MeasureString(titleFace, line).Ceil()) / 2
		}
		d.Dot = fixed.P(x, y+titleFace.Metrics().Ascent.Ceil())
		d.DrawString(line)
		y += titleHeight
	}
	d.Face = bodyFace
	for _, line := range bodyLines {
		x := margin
		if centered {
			x = (w - font.MeasureString(bodyFace, line).Ceil()) / 2
		}
		d.Dot = fixed.P(x, y+bodyFace.Metrics().Ascent.Ceil())
		d.DrawString(line)
		y += bodyHeight
	}
	return canvas, nil
}

func typesetDetailSection(ctx context.Context, publicID, sourceURL string, section map[string]interface{}, typeface *opentype.Font) (string, error) {
	if objectStore == nil {
		return "", fmt.Errorf("详情排版对象存储未初始化")
	}
	data, _, err := loadMediaBytes(ctx, sourceURL)
	if err != nil {
		return "", err
	}
	config, _, err := image.DecodeConfig(bytes.NewReader(data))
	if err != nil || config.Width > 4096 || config.Height > 8192 {
		return "", fmt.Errorf("详情底图无效或尺寸超出安全范围")
	}
	img, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		return "", err
	}
	result, err := layoutDetailModule(img, section, typeface)
	if err != nil {
		return "", err
	}
	var encoded bytes.Buffer
	if err := jpeg.Encode(&encoded, result, &jpeg.Options{Quality: 92}); err != nil {
		return "", err
	}
	name := fmt.Sprintf("workflows/%s/detail-module-%d.jpg", publicID, time.Now().UnixNano())
	return objectStore.Upload(ctx, name, "image/jpeg", bytes.NewReader(encoded.Bytes()), int64(encoded.Len()))
}
